import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';

const componentCode = [
  "import { Component, signal, type WritableSignal } from '@angular/core';",
  "import type { TngFlowDefinition, TngFlowNode } from '@tailng-ui/flow';",
  'import {',
  '  TngFlowNodePropertiesComponent,',
  '  TngFlowNodePropertiesDataTemplateDirective,',
  '  type TngFlowNodePropertyChangeRequest,',
  "} from '@tailng-ui/flow/execution';",
  '',
  'type AgentNodeData = Readonly<{',
  '  owner: string;',
  '  risk: string;',
  '  sla: string;',
  '}>;',
  '',
  'const initialDefinition: TngFlowDefinition<AgentNodeData> = {',
  "  id: 'support-agent-properties',",
  "  name: 'Support agent properties',",
  '  connections: [],',
  '  nodes: [',
  '    {',
  "      id: 'classify-ticket',",
  "      type: 'model',",
  "      name: 'Classify ticket',",
  "      description: 'Categorizes inbound requests before routing.',",
  '      position: { x: 0, y: 0 },',
  "      data: { owner: 'AI platform', risk: 'Low', sla: '15 min' },",
  '      ports: [',
  "        { id: 'input', direction: 'input', kind: 'data', label: 'Ticket', dataType: 'json', required: true },",
  "        { id: 'output', direction: 'output', kind: 'data', label: 'Category', dataType: 'string' },",
  '      ],',
  '    },',
  '  ],',
  '};',
  '',
  'function cloneDefinition(): TngFlowDefinition<AgentNodeData> {',
  '  return {',
  '    ...initialDefinition,',
  '    nodes: initialDefinition.nodes.map((node) => ({',
  '      ...node,',
  '      position: { ...node.position },',
  '      data: node.data === undefined ? undefined : { ...node.data },',
  '      ports: node.ports?.map((port) => ({ ...port })),',
  '    })),',
  '  };',
  '}',
  '',
  '@Component({',
  "  selector: 'app-agent-node-properties',",
  '  standalone: true,',
  '  imports: [TngFlowNodePropertiesComponent, TngFlowNodePropertiesDataTemplateDirective],',
  "  templateUrl: './agent-node-properties.component.html',",
  "  styleUrl: './agent-node-properties.component.css',",
  '})',
  'export class AgentNodePropertiesComponent {',
  '  protected readonly definition = signal<TngFlowDefinition<AgentNodeData>>(cloneDefinition());',
  "  protected readonly inspectedNodeId = signal<string | null>('classify-ticket');",
  '  protected readonly readonly = signal(false);',
  '',
  '  protected applyNodeChanges(request: TngFlowNodePropertyChangeRequest<AgentNodeData>): void {',
  '    this.definition.update((definition) => ({',
  '      ...definition,',
  '      nodes: definition.nodes.map((node) =>',
  '        node.id === request.nodeId ? { ...node, ...request.changes } : node,',
  '      ),',
  '    }));',
  '  }',
  '',
  '  protected updateOwner(',
  '    data: AgentNodeData | undefined,',
  '    event: Event,',
  '    requestDataChange: (data: AgentNodeData) => void,',
  '  ): void {',
  '    requestDataChange({ ...this.withDefaults(data), owner: this.readValue(event) });',
  '  }',
  '',
  '  protected updateRisk(',
  '    data: AgentNodeData | undefined,',
  '    event: Event,',
  '    requestDataChange: (data: AgentNodeData) => void,',
  '  ): void {',
  '    requestDataChange({ ...this.withDefaults(data), risk: this.readValue(event) });',
  '  }',
  '',
  '  protected updateSla(',
  '    data: AgentNodeData | undefined,',
  '    event: Event,',
  '    requestDataChange: (data: AgentNodeData) => void,',
  '  ): void {',
  '    requestDataChange({ ...this.withDefaults(data), sla: this.readValue(event) });',
  '  }',
  '',
  '  protected dataOwner(data: AgentNodeData | undefined): string {',
  '    return this.withDefaults(data).owner;',
  '  }',
  '',
  '  protected dataRisk(data: AgentNodeData | undefined): string {',
  '    return this.withDefaults(data).risk;',
  '  }',
  '',
  '  protected dataSla(data: AgentNodeData | undefined): string {',
  '    return this.withDefaults(data).sla;',
  '  }',
  '',
  '  protected selectNode(node: TngFlowNode<AgentNodeData>): void {',
  '    this.inspectedNodeId.set(node.id);',
  '  }',
  '',
  '  private withDefaults(data: AgentNodeData | undefined): AgentNodeData {',
  "    return data ?? { owner: 'Unassigned', risk: 'Low', sla: '30 min' };",
  '  }',
  '',
  '  private readValue(event: Event): string {',
  '    return event.target instanceof HTMLInputElement || event.target instanceof HTMLSelectElement',
  '      ? event.target.value',
  "      : '';",
  '  }',
  '}',
].join('\n');

const plainCssMarkup = [
  '<div class="agent-node-properties-demo">',
  '  <aside class="agent-node-properties-demo__nodes" aria-label="Workflow nodes">',
  '    @for (node of definition().nodes; track node.id) {',
  '      <button',
  '        type="button"',
  '        [class.is-selected]="inspectedNodeId() === node.id"',
  '        (click)="selectNode(node)"',
  '      >',
  '        <span>{{ node.name }}</span>',
  '        <small>{{ node.type }}</small>',
  '      </button>',
  '    }',
  '  </aside>',
  '',
  '  <tng-flow-node-properties',
  '    class="agent-node-properties-demo__panel"',
  '    [definition]="definition()"',
  '    [inspectedNodeId]="inspectedNodeId()"',
  '    [readonly]="readonly()"',
  '    (nodeChangeRequested)="applyNodeChanges($event)"',
  '  >',
  '    <ng-template',
  '      tngFlowNodePropertiesData',
  '      let-data',
  '      let-readonly="readonly"',
  '      let-requestDataChange="requestDataChange"',
  '    >',
  '      <div class="agent-node-properties-demo__data-grid">',
  '        <label>',
  '          <span>Owner</span>',
  '          <input type="text" [value]="dataOwner(data)" [readOnly]="readonly" (input)="updateOwner(data, $event, requestDataChange)" />',
  '        </label>',
  '        <label>',
  '          <span>Risk</span>',
  '          <select [value]="dataRisk(data)" [disabled]="readonly" (change)="updateRisk(data, $event, requestDataChange)">',
  '            <option>Low</option>',
  '            <option>Medium</option>',
  '            <option>High</option>',
  '          </select>',
  '        </label>',
  '        <label>',
  '          <span>SLA</span>',
  '          <input type="text" [value]="dataSla(data)" [readOnly]="readonly" (input)="updateSla(data, $event, requestDataChange)" />',
  '        </label>',
  '      </div>',
  '    </ng-template>',
  '  </tng-flow-node-properties>',
  '</div>',
].join('\n');

const plainCssStyles = [
  '.agent-node-properties-demo {',
  '  display: grid;',
  '  grid-template-columns: minmax(12rem, 16rem) minmax(0, 1fr);',
  '  min-height: 34rem;',
  '  overflow: hidden;',
  '  border: 1px solid var(--tng-semantic-border-subtle);',
  '  border-radius: 0.5rem;',
  '}',
  '',
  '.agent-node-properties-demo__nodes {',
  '  display: grid;',
  '  align-content: start;',
  '  gap: 0.5rem;',
  '  padding: 0.75rem;',
  '  border-right: 1px solid var(--tng-semantic-border-subtle);',
  '}',
  '',
  '.agent-node-properties-demo__nodes button {',
  '  display: grid;',
  '  gap: 0.2rem;',
  '  padding: 0.65rem 0.75rem;',
  '  border: 1px solid var(--tng-semantic-border-subtle);',
  '  border-radius: 0.5rem;',
  '  text-align: left;',
  '}',
  '',
  '.agent-node-properties-demo__nodes button.is-selected {',
  '  border-color: var(--tng-semantic-accent-primary);',
  '}',
  '',
  '.agent-node-properties-demo__panel {',
  '  min-height: 34rem;',
  '}',
  '',
  '.agent-node-properties-demo__data-grid {',
  '  display: grid;',
  '  gap: 0.75rem;',
  '}',
  '',
  '@media (max-width: 720px) {',
  '  .agent-node-properties-demo {',
  '    grid-template-columns: 1fr;',
  '  }',
  '}',
].join('\n');

const tailwindMarkup = [
  '<div class="grid min-h-[34rem] overflow-hidden rounded-lg border border-tng-border-subtle bg-tng-bg-base md:grid-cols-[minmax(12rem,16rem)_minmax(0,1fr)]">',
  '  <aside class="grid content-start gap-2 border-b border-tng-border-subtle p-3 md:border-b-0 md:border-r" aria-label="Workflow nodes">',
  '    @for (node of definition().nodes; track node.id) {',
  '      <button',
  '        type="button"',
  '        class="grid gap-0.5 rounded-lg border border-tng-border-subtle px-3 py-2 text-left text-sm text-tng-fg-primary transition hover:bg-tng-bg-muted"',
  '        [class.border-tng-accent-primary]="inspectedNodeId() === node.id"',
  '        (click)="selectNode(node)"',
  '      >',
  '        <span class="font-semibold">{{ node.name }}</span>',
  '        <small class="text-xs uppercase text-tng-fg-muted">{{ node.type }}</small>',
  '      </button>',
  '    }',
  '  </aside>',
  '',
  '  <tng-flow-node-properties class="min-h-[34rem]" [definition]="definition()" [inspectedNodeId]="inspectedNodeId()" [readonly]="readonly()" (nodeChangeRequested)="applyNodeChanges($event)">',
  '    <ng-template tngFlowNodePropertiesData let-data let-readonly="readonly" let-requestDataChange="requestDataChange">',
  '      <div class="grid gap-3">',
  '        <label class="grid gap-1.5 text-sm text-tng-fg-secondary">',
  '          <span>Owner</span>',
  '          <input class="min-h-10 rounded-lg border border-tng-border-default bg-tng-bg-surface px-3 text-tng-fg-primary" type="text" [value]="dataOwner(data)" [readOnly]="readonly" (input)="updateOwner(data, $event, requestDataChange)" />',
  '        </label>',
  '        <label class="grid gap-1.5 text-sm text-tng-fg-secondary">',
  '          <span>Risk</span>',
  '          <select class="min-h-10 rounded-lg border border-tng-border-default bg-tng-bg-surface px-3 text-tng-fg-primary" [value]="dataRisk(data)" [disabled]="readonly" (change)="updateRisk(data, $event, requestDataChange)">',
  '            <option>Low</option>',
  '            <option>Medium</option>',
  '            <option>High</option>',
  '          </select>',
  '        </label>',
  '        <label class="grid gap-1.5 text-sm text-tng-fg-secondary">',
  '          <span>SLA</span>',
  '          <input class="min-h-10 rounded-lg border border-tng-border-default bg-tng-bg-surface px-3 text-tng-fg-primary" type="text" [value]="dataSla(data)" [readOnly]="readonly" (input)="updateSla(data, $event, requestDataChange)" />',
  '        </label>',
  '      </div>',
  '    </ng-template>',
  '  </tng-flow-node-properties>',
  '</div>',
].join('\n');

export const flowNodePropertiesOverviewPlainCssCodeTabs: readonly DocsExampleCodeTab[] =
  Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'agent-node-properties.component.ts',
      code: componentCode,
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'agent-node-properties.component.html',
      code: plainCssMarkup,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'agent-node-properties.component.css',
      code: plainCssStyles,
    },
  ]);

export const flowNodePropertiesOverviewTailwindCodeTabs: readonly DocsExampleCodeTab[] =
  Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'agent-node-properties.component.ts',
      code: componentCode,
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'agent-node-properties.component.html',
      code: tailwindMarkup,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'agent-node-properties.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);
