import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';

const controlledComponentCode = [
  "import { Component, signal } from '@angular/core';",
  'import {',
  '  TngFlowEditorComponent,',
  '  TngFlowPaletteItemDirective,',
  '  type TngFlowConnection,',
  '  type TngFlowConnectionCreateRequest,',
  '  type TngFlowNode,',
  '  type TngFlowNodeCreateRequest,',
  '  type TngFlowNodesMovedEvent,',
  '  type TngFlowPaletteItem,',
  '  type TngFlowPresentation,',
  '  type TngFlowValidation,',
  "} from '@tailng-ui/flow';",
  "import { agentConnections, agentNodes } from './agent-flow.data';",
  '',
  'const paletteItems: readonly TngFlowPaletteItem[] = [',
  '  {',
  "    id: 'human-review-catalog-item',",
  "    type: 'review',",
  "    name: 'Human review',",
  "    description: 'Pause the workflow for an approval decision.',",
  '  },',
  '];',
  '',
  '@Component({',
  "  selector: 'app-agent-flow',",
  '  standalone: true,',
  '  imports: [TngFlowEditorComponent, TngFlowPaletteItemDirective],',
  "  templateUrl: './agent-flow.component.html',",
  '})',
  'export class AgentFlowComponent {',
  '  protected readonly nodes = signal<readonly TngFlowNode[]>(agentNodes);',
  '  protected readonly connections = signal<readonly TngFlowConnection[]>(agentConnections);',
  '  protected readonly presentation: TngFlowPresentation = {',
  "    nodes: { model: { status: 'running', progress: 68 } },",
  '  };',
  '  protected readonly validation: TngFlowValidation = { issues: [] };',
  '  protected readonly paletteItems = paletteItems;',
  '  private nodeSequence = 0;',
  '',
  '  protected createNode(event: TngFlowNodeCreateRequest): void {',
  '    const id = `${event.item.type}-${this.nodeSequence++}`;',
  '    this.nodes.update((nodes) => [',
  '      ...nodes,',
  '      {',
  '        id,',
  '        type: event.item.type,',
  '        name: event.item.name,',
  '        description: event.item.description,',
  '        data: event.item.data,',
  '        icon: event.item.icon,',
  '        position: event.position,',
  '        ports: [],',
  '      },',
  '    ]);',
  '  }',
  '',
  '  protected moveNodes(event: TngFlowNodesMovedEvent): void {',
  '    const positions = new Map(event.nodes.map((node) => [node.id, node.position]));',
  '    this.nodes.update((nodes) =>',
  '      nodes.map((node) => ({ ...node, position: positions.get(node.id) ?? node.position })),',
  '    );',
  '  }',
  '',
  '  protected createConnection(event: TngFlowConnectionCreateRequest): void {',
  '    this.connections.update((connections) => [',
  '      ...connections,',
  '      {',
  '        id: crypto.randomUUID(),',
  '        source: event.source,',
  '        target: event.target,',
  "        type: 'bezier',",
  '      },',
  '    ]);',
  '  }',
  '}',
].join('\n');

const plainCssEditorMarkup = [
  '<div class="agent-workflow-builder">',
  '  <aside class="agent-workflow-palette" aria-label="Workflow node palette">',
  '    @for (item of paletteItems; track item.id) {',
  '      <button',
  '        type="button"',
  '        [tngFlowPaletteItem]="item"',
  '        (tngFlowPaletteItemActivate)="',
  '          editor.requestNodeCreate($event.item, undefined, $event.source)',
  '        "',
  '      >',
  '        {{ item.name }}',
  '      </button>',
  '    }',
  '  </aside>',
  '',
  '  <tng-flow-editor',
  '    #editor="tngFlowEditor"',
  '    flowId="agent-workflow"',
  '    class="agent-workflow"',
  '    ariaLabel="Interactive customer support agent workflow"',
  '    [nodes]="nodes()"',
  '    [connections]="connections()"',
  '    [presentation]="presentation"',
  '    [validation]="validation"',
  '    [smartGuides]="{ enabled: true, disableModifier: \'alt\' }"',
  '    [showMinimap]="true"',
  '    (nodeCreateRequested)="createNode($event)"',
  '    (nodesMoved)="moveNodes($event)"',
  '    (connectionCreateRequested)="createConnection($event)"',
  '  />',
  '</div>',
].join('\n');

const tailwindEditorMarkup = [
  '<div class="grid gap-3 lg:grid-cols-[15rem_minmax(0,1fr)]">',
  '  <aside class="grid content-start gap-2 rounded-xl border p-3"',
  '    aria-label="Workflow node palette">',
  '    @for (item of paletteItems; track item.id) {',
  '      <button',
  '        type="button"',
  '        class="cursor-grab rounded-lg border p-3 text-left"',
  '        [tngFlowPaletteItem]="item"',
  '        (tngFlowPaletteItemActivate)="',
  '          editor.requestNodeCreate($event.item, undefined, $event.source)',
  '        "',
  '      >',
  '        {{ item.name }}',
  '      </button>',
  '    }',
  '  </aside>',
  '',
  '  <tng-flow-editor',
  '    #editor="tngFlowEditor"',
  '    flowId="agent-workflow"',
  '    class="block h-[min(70vh,48rem)] min-h-[25rem]"',
  '    ariaLabel="Interactive customer support agent workflow"',
  '    [nodes]="nodes()"',
  '    [connections]="connections()"',
  '    [presentation]="presentation"',
  '    [validation]="validation"',
  '    [smartGuides]="{ enabled: true, disableModifier: \'alt\' }"',
  '    [showMinimap]="true"',
  '    (nodeCreateRequested)="createNode($event)"',
  '    (nodesMoved)="moveNodes($event)"',
  '    (connectionCreateRequested)="createConnection($event)"',
  '  />',
  '</div>',
].join('\n');

export const flowEditorOverviewPlainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'agent-flow.component.ts',
    code: controlledComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'agent-flow.component.html',
    code: plainCssEditorMarkup,
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'agent-flow.component.css',
    code: [
      '.agent-workflow {',
      '  display: block;',
      '  height: min(70vh, 48rem);',
      '  min-height: 25rem;',
      '}',
      '',
      '.agent-workflow-builder {',
      '  display: grid;',
      '  grid-template-columns: 15rem minmax(0, 1fr);',
      '  gap: 0.75rem;',
      '}',
      '',
      '.agent-workflow-palette {',
      '  display: grid;',
      '  align-content: start;',
      '  gap: 0.5rem;',
      '}',
    ].join('\n'),
  },
]);

export const flowEditorOverviewTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'agent-flow.component.ts',
    code: controlledComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'agent-flow.component.html',
    code: tailwindEditorMarkup,
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'agent-flow.component.css',
    code: '/* Tailwind utilities are applied directly in the template. */',
  },
]);
