/* eslint-disable max-lines-per-function -- The copy-ready controlled authoring example is kept together. */
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';

const componentCode = [
  "import { Component, computed, signal } from '@angular/core';",
  "import { TngButtonComponent } from '@tailng-ui/components';",
  'import {',
  '  commitTngFlowHistory,',
  '  createTngFlowHistory,',
  '  ensureTngFlowCustomPointPorts,',
  '  pruneUnusedTngFlowCustomPointPorts,',
  '  redoTngFlowHistory,',
  '  tngFlowHistoryStatus,',
  '  undoTngFlowHistory,',
  '  type TngFlowConnectionCreateRequest,',
  '  type TngFlowConnectionReconnectRequest,',
  '  type TngFlowConnectionRoutingChangeRequest,',
  '  type TngFlowConnectionsDeleteRequest,',
  '  type TngFlowDefinition,',
  '  type TngFlowEditorCommandRequest,',
  '  type TngFlowEditorMode,',
  '  type TngFlowNodesDeleteRequest,',
  '  type TngFlowNodesMovedEvent,',
  '  type TngFlowSelection,',
  '  type TngFlowViewport,',
  "} from '@tailng-ui/flow';",
  "import { TngFlowExecutionGraphComponent } from '@tailng-ui/flow/execution';",
  "import { runningSnapshot, supportWorkflow } from './support-workflow.data';",
  '',
  '@Component({',
  "  selector: 'app-running-workflow-graph',",
  '  standalone: true,',
  '  imports: [TngButtonComponent, TngFlowExecutionGraphComponent],',
  "  templateUrl: './running-workflow-graph.component.html',",
  "  styleUrl: './running-workflow-graph.component.css',",
  '})',
  'export class RunningWorkflowGraphComponent {',
  '  protected readonly definition = signal<TngFlowDefinition<unknown>>(supportWorkflow);',
  '  protected readonly snapshot = runningSnapshot;',
  "  protected readonly mode = signal<TngFlowEditorMode>('edit');",
  "  protected readonly modes: readonly TngFlowEditorMode[] = ['edit', 'inspect', 'readonly'];",
  '  protected readonly selection = signal<TngFlowSelection>({',
  "    nodeIds: new Set(['risk']),",
  '    connectionIds: new Set(),',
  '  });',
  "  protected readonly inspectedNodeId = signal<string | null>('risk');",
  "  protected readonly selectedExecutionId = signal<string | null>('running-node-risk');",
  '  protected readonly viewport = signal<TngFlowViewport>({',
  '    position: { x: -80, y: -75 },',
  '    scale: 0.68,',
  '  });',
  '  protected readonly history = signal(',
  '    createTngFlowHistory(this.definition(), { selection: this.selection() }),',
  '  );',
  '  protected readonly historyStatus = computed(() => tngFlowHistoryStatus(this.history()));',
  '',
  '  protected onNodesMoved(event: TngFlowNodesMovedEvent): void {',
  '    const positions = new Map(event.nodes.map((move) => [move.id, move.position]));',
  '    this.commitDefinitionUpdate(',
  "      'Move nodes',",
  '      (definition) => ({',
  '      ...definition,',
  '      nodes: definition.nodes.map((node) => {',
  '        const position = positions.get(node.id);',
  '        return position === undefined ? node : { ...node, position };',
  '      }),',
  '      }),',
  '    );',
  '  }',
  '',
  '  protected onConnectionCreateRequested(request: TngFlowConnectionCreateRequest): void {',
  '    const definition = this.definition();',
  '    const id = this.nextConnectionId();',
  '    const nodes = ensureTngFlowCustomPointPorts(definition.nodes, [',
  '      request.source,',
  '      request.target,',
  '    ]);',
  '    this.applyControlledUpdate(',
  "      'Create connection',",
  '      {',
  '        ...definition,',
  '        nodes,',
  '        connections: [',
  '          ...definition.connections,',
  '          {',
  '            id,',
  '            source: request.source,',
  '            target: request.target,',
  "            routing: request.routing ?? { type: 'bezier' },",
  '          },',
  '        ],',
  '      },',
  '      { nodeIds: new Set(), connectionIds: new Set([id]) },',
  '    );',
  '  }',
  '',
  '  protected onConnectionReconnectRequested(request: TngFlowConnectionReconnectRequest): void {',
  '    const definition = this.definition();',
  '    const nodes = ensureTngFlowCustomPointPorts(definition.nodes, [',
  '      request.source,',
  '      request.target,',
  '    ]);',
  '    const connections = definition.connections.map((connection) =>',
  '      connection.id === request.connectionId',
  '        ? { ...connection, source: request.source, target: request.target }',
  '        : connection,',
  '    );',
  '    this.applyControlledUpdate(',
  "      'Reconnect connection',",
  '      pruneUnusedTngFlowCustomPointPorts({ ...definition, nodes, connections }),',
  '      this.selection(),',
  '    );',
  '  }',
  '',
  '  protected onConnectionsDeleteRequested(request: TngFlowConnectionsDeleteRequest): void {',
  '    const deletedIds = new Set(request.connectionIds);',
  '    const selection = this.selection();',
  '    this.applyControlledUpdate(',
  "      'Delete connections',",
  '      pruneUnusedTngFlowCustomPointPorts({',
  '        ...this.definition(),',
  '        connections: this.definition().connections.filter(',
  '          (connection) => !deletedIds.has(connection.id),',
  '        ),',
  '      }),',
  '      {',
  '        nodeIds: new Set(selection.nodeIds),',
  '        connectionIds: new Set(',
  '          [...selection.connectionIds].filter((connectionId) => !deletedIds.has(connectionId)),',
  '        ),',
  '      },',
  '    );',
  '  }',
  '',
  '  protected onNodesDeleteRequested(request: TngFlowNodesDeleteRequest): void {',
  '    const deletedNodeIds = new Set(request.nodeIds);',
  '    const definition = this.definition();',
  '    const selection = this.selection();',
  '    const removedConnectionIds = new Set(',
  '      definition.connections',
  '        .filter(',
  '          (connection) =>',
  '            deletedNodeIds.has(connection.source.nodeId) ||',
  '            deletedNodeIds.has(connection.target.nodeId),',
  '        )',
  '        .map((connection) => connection.id),',
  '    );',
  '    this.applyControlledUpdate(',
  "      'Delete nodes',",
  '      pruneUnusedTngFlowCustomPointPorts({',
  '        ...definition,',
  '        nodes: definition.nodes.filter((node) => !deletedNodeIds.has(node.id)),',
  '        connections: definition.connections.filter(',
  '          (connection) => !removedConnectionIds.has(connection.id),',
  '        ),',
  '      }),',
  '      {',
  '        nodeIds: new Set([...selection.nodeIds].filter((nodeId) => !deletedNodeIds.has(nodeId))),',
  '        connectionIds: new Set(',
  '          [...selection.connectionIds].filter(',
  '            (connectionId) => !removedConnectionIds.has(connectionId),',
  '          ),',
  '        ),',
  '      },',
  '    );',
  "    if (this.inspectedNodeId() !== null && request.nodeIds.includes(this.inspectedNodeId() ?? '')) {",
  '      this.inspectedNodeId.set(null);',
  '      this.selectedExecutionId.set(null);',
  '    }',
  '  }',
  '',
  '  protected onConnectionRoutingChangeRequested(',
  '    request: TngFlowConnectionRoutingChangeRequest,',
  '  ): void {',
  '    const connectionIds = new Set(request.connectionIds);',
  '    this.commitDefinitionUpdate(',
  '      `Change ${request.type} routing`,',
  '      (definition) => ({',
  '        ...definition,',
  '        connections: definition.connections.map((connection) =>',
  '          connectionIds.has(connection.id)',
  '            ? { ...connection, routing: { ...connection.routing, type: request.type } }',
  '            : connection,',
  '        ),',
  '      }),',
  '    );',
  '  }',
  '',
  '  protected onCommandRequested(request: TngFlowEditorCommandRequest): void {',
  "    if (request.command === 'undo') {",
  '      this.applyHistoryState(undoTngFlowHistory(this.history()));',
  '      return;',
  '    }',
  "    if (request.command === 'redo') {",
  '      this.applyHistoryState(redoTngFlowHistory(this.history()));',
  '    }',
  '  }',
  '',
  '  protected deleteSelectedConnections(): void {',
  '    this.onConnectionsDeleteRequested({',
  '      connectionIds: [...this.selection().connectionIds],',
  "      source: 'api',",
  '    });',
  '  }',
  '',
  '  private commitDefinitionUpdate(',
  '    label: string,',
  '    update: (definition: TngFlowDefinition<unknown>) => TngFlowDefinition<unknown>,',
  '  ): void {',
  '    this.applyControlledUpdate(label, update(this.definition()), this.selection());',
  '  }',
  '',
  '  private applyControlledUpdate(',
  '    label: string,',
  '    definition: TngFlowDefinition<unknown>,',
  '    selection: TngFlowSelection,',
  '  ): void {',
  '    this.definition.set(definition);',
  '    this.selection.set(selection);',
  '    this.history.update((history) =>',
  '      commitTngFlowHistory(history, definition, { label, selection }),',
  '    );',
  '  }',
  '',
  '  private applyHistoryState(history: ReturnType<typeof undoTngFlowHistory>): void {',
  '    const selection = history.present.selection ?? { nodeIds: new Set(), connectionIds: new Set() };',
  '    const selectedNodeId = selection.nodeIds.values().next().value;',
  '',
  '    this.history.set(history);',
  '    this.definition.set(history.present.definition);',
  '    this.selection.set(selection);',
  "    if (typeof selectedNodeId === 'string') {",
  '      this.inspectedNodeId.set(selectedNodeId);',
  '      this.selectedExecutionId.set(null);',
  '      return;',
  '    }',
  '    if (',
  '      this.inspectedNodeId() !== null &&',
  '      !history.present.definition.nodes.some((node) => node.id === this.inspectedNodeId())',
  '    ) {',
  '      this.inspectedNodeId.set(null);',
  '      this.selectedExecutionId.set(null);',
  '    }',
  '  }',
  '',
  '  private nextConnectionId(): string {',
  '    const ids = new Set(this.definition().connections.map((connection) => connection.id));',
  '    let suffix = 1;',
  '    while (ids.has(`connection-${suffix}`)) {',
  '      suffix += 1;',
  '    }',
  '    return `connection-${suffix}`;',
  '  }',
  '}',
].join('\n');

function graphMarkup(
  className: string,
  modePickerClass = 'graph-mode-picker',
  editingHintClass = 'graph-editing-hint',
): string {
  return [
    `<div class="${modePickerClass}" aria-label="Graph interaction mode">`,
    '  @for (graphMode of modes; track graphMode) {',
    '    <tng-button',
    '      size="sm"',
    "      [appearance]=\"mode() === graphMode ? 'solid' : 'outline'\"",
    '      [ariaPressed]="mode() === graphMode"',
    '      (click)="mode.set(graphMode)"',
    '    >',
    '      {{ graphMode }}',
    '    </tng-button>',
    '  }',
    "  @if (mode() === 'edit' && selection().connectionIds.size > 0) {",
    '    <tng-button appearance="outline" size="sm" (click)="deleteSelectedConnections()">',
    '      Delete connection',
    '    </tng-button>',
    '  }',
    '</div>',
    '',
    "@if (mode() === 'edit') {",
    `  <p class="${editingHintClass}">`,
    '    Select a node to reveal connection points. Drag to connect; select a connection and press Delete or Backspace to remove it.',
    '  </p>',
    '}',
    '',
    '<tng-flow-execution-graph',
    '  flowId="running-workflow"',
    '  ariaLabel="Running support workflow execution graph"',
    `  class="${className}"`,
    '  [definition]="definition()"',
    '  [snapshot]="snapshot"',
    '  [selection]="selection()"',
    '  [inspectedNodeId]="inspectedNodeId()"',
    '  [selectedExecutionId]="selectedExecutionId()"',
    '  [viewport]="viewport()"',
    '  [mode]="mode()"',
    '  attachmentLayout="custom-points"',
    '  [showMinimap]="true"',
    '  [showControls]="true"',
    '  [showSelectionArea]="false"',
    '  [fitOnInit]="true"',
    "  [commandShortcuts]=\"['undo', 'redo']\"",
    '  [canUndo]="historyStatus().canUndo"',
    '  [canRedo]="historyStatus().canRedo"',
    '  (nodesMoved)="onNodesMoved($event)"',
    '  (nodesDeleteRequested)="onNodesDeleteRequested($event)"',
    '  (connectionCreateRequested)="onConnectionCreateRequested($event)"',
    '  (connectionReconnectRequested)="onConnectionReconnectRequested($event)"',
    '  (connectionRoutingChangeRequested)="onConnectionRoutingChangeRequested($event)"',
    '  (connectionsDeleteRequested)="onConnectionsDeleteRequested($event)"',
    '  (commandRequested)="onCommandRequested($event)"',
    '  (selectionChange)="selection.set($event)"',
    '  (inspectedNodeIdChange)="inspectedNodeId.set($event)"',
    '  (selectedExecutionIdChange)="selectedExecutionId.set($event)"',
    '  (viewportChange)="viewport.set($event)"',
    '/>',
  ].join('\n');
}

function codeTabs(html: string, css: string): readonly DocsExampleCodeTab[] {
  return Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'running-workflow-graph.component.ts',
      code: componentCode,
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'running-workflow-graph.component.html',
      code: html,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'running-workflow-graph.component.css',
      code: css,
    },
  ]);
}

export const flowExecutionGraphOverviewPlainCssCodeTabs = codeTabs(
  graphMarkup('running-workflow-graph'),
  [
    '.graph-mode-picker {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: 0.5rem;',
    '  margin-bottom: 0.5rem;',
    '}',
    '',
    '.graph-editing-hint {',
    '  color: var(--tng-semantic-foreground-secondary);',
    '  font-size: 0.75rem;',
    '  margin: 0 0 0.75rem;',
    '}',
    '',
    '.running-workflow-graph {',
    '  display: block;',
    '  height: 28rem;',
    '  min-height: 24rem;',
    '  overflow: hidden;',
    '  border: 1px solid var(--tng-semantic-border-subtle);',
    '  border-radius: 0.5rem;',
    '}',
  ].join('\n'),
);

export const flowExecutionGraphOverviewTailwindCodeTabs = codeTabs(
  graphMarkup(
    'block h-[28rem] min-h-[24rem] overflow-hidden rounded-lg border border-tng-border-subtle bg-tng-bg-base',
    'mb-3 flex flex-wrap gap-2',
    'mb-3 text-xs text-tng-fg-secondary',
  ),
  '/* Tailwind utilities are applied directly in the template. */',
);
