import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';

const componentCode = [
  "import { Component, signal } from '@angular/core';",
  "import type { TngFlowDefinition, TngFlowNode } from '@tailng-ui/flow';",
  'import {',
  '  TngFlowNodePropertiesComponent,',
  '  TngFlowNodePropertiesDataTemplateDirective,',
  '  type TngFlowNodePropertyChangeRequest,',
  "} from '@tailng-ui/flow/execution';",
  '',
  'type IncidentNodeData = Readonly<{',
  '  escalation: string;',
  '  owner: string;',
  "  priority: 'Normal' | 'High' | 'Critical';",
  '  queue: string;',
  '}>;',
  '',
  'const initialDefinition: TngFlowDefinition<IncidentNodeData> = {',
  "  id: 'incident-triage-properties',",
  "  name: 'Incident triage workflow',",
  '  connections: [],',
  '  nodes: [',
  '    {',
  "      id: 'classify-impact',",
  "      type: 'model',",
  "      name: 'Classify impact',",
  "      description: 'Scores customer impact and suggests a response lane.',",
  '      position: { x: 0, y: 0 },',
  '      data: {',
  "        escalation: 'Incident commander',",
  "        owner: 'AI operations',",
  "        priority: 'Critical',",
  "        queue: 'Incident response',",
  '      },',
  '      ports: [',
  "        { id: 'normalized', direction: 'input', kind: 'data', label: 'Normalized alert', dataType: 'json', required: true },",
  "        { id: 'classification', direction: 'output', kind: 'data', label: 'Classification', dataType: 'json' },",
  "        { id: 'manual-review', direction: 'output', kind: 'control', label: 'Manual review' },",
  '      ],',
  '    },',
  '  ],',
  '};',
  '',
  'function cloneDefinition(): TngFlowDefinition<IncidentNodeData> {',
  '  return {',
  '    ...initialDefinition,',
  '    nodes: initialDefinition.nodes.map((node) => ({',
  '      ...node,',
  '      position: { ...node.position },',
  '      data: node.data === undefined ? undefined : { ...node.data },',
  '      ports: node.ports?.map((port) => ({ ...port })),',
  '    })),',
  '  };',
  '}',
  '',
  '@Component({',
  "  selector: 'app-incident-node-properties',",
  '  standalone: true,',
  '  imports: [TngFlowNodePropertiesComponent, TngFlowNodePropertiesDataTemplateDirective],',
  "  templateUrl: './incident-node-properties.component.html',",
  "  styleUrl: './incident-node-properties.component.css',",
  '})',
  'export class IncidentNodePropertiesComponent {',
  '  protected readonly definition = signal<TngFlowDefinition<IncidentNodeData>>(cloneDefinition());',
  "  protected readonly inspectedNodeId = signal<string | null>('classify-impact');",
  '  protected readonly readonly = signal(false);',
  '  protected readonly showData = signal(true);',
  '  protected readonly showPorts = signal(true);',
  "  protected readonly priorities = ['Normal', 'High', 'Critical'] as const;",
  '',
  '  protected selectNode(node: TngFlowNode<IncidentNodeData>): void {',
  '    this.inspectedNodeId.set(node.id);',
  '  }',
  '',
  '  protected applyNodeChanges(',
  '    request: TngFlowNodePropertyChangeRequest<IncidentNodeData>,',
  '  ): void {',
  '    this.definition.update((definition) => ({',
  '      ...definition,',
  '      nodes: definition.nodes.map((node) =>',
  '        node.id === request.nodeId ? { ...node, ...request.changes } : node,',
  '      ),',
  '    }));',
  '  }',
  '',
  '  protected updateOwner(',
  '    data: IncidentNodeData | undefined,',
  '    event: Event,',
  '    requestDataChange: (data: IncidentNodeData) => void,',
  '  ): void {',
  '    requestDataChange({ ...this.withDefaults(data), owner: this.readValue(event) });',
  '  }',
  '',
  '  protected updateQueue(',
  '    data: IncidentNodeData | undefined,',
  '    event: Event,',
  '    requestDataChange: (data: IncidentNodeData) => void,',
  '  ): void {',
  '    requestDataChange({ ...this.withDefaults(data), queue: this.readValue(event) });',
  '  }',
  '',
  '  protected updatePriority(',
  '    data: IncidentNodeData | undefined,',
  '    event: Event,',
  '    requestDataChange: (data: IncidentNodeData) => void,',
  '  ): void {',
  '    requestDataChange({',
  '      ...this.withDefaults(data),',
  '      priority: this.toPriority(this.readValue(event)),',
  '    });',
  '  }',
  '',
  '  protected updateEscalation(',
  '    data: IncidentNodeData | undefined,',
  '    event: Event,',
  '    requestDataChange: (data: IncidentNodeData) => void,',
  '  ): void {',
  '    requestDataChange({ ...this.withDefaults(data), escalation: this.readValue(event) });',
  '  }',
  '',
  '  protected dataOwner(data: IncidentNodeData | undefined): string {',
  '    return this.withDefaults(data).owner;',
  '  }',
  '',
  '  protected dataQueue(data: IncidentNodeData | undefined): string {',
  '    return this.withDefaults(data).queue;',
  '  }',
  '',
  "  protected dataPriority(data: IncidentNodeData | undefined): IncidentNodeData['priority'] {",
  '    return this.withDefaults(data).priority;',
  '  }',
  '',
  '  protected dataEscalation(data: IncidentNodeData | undefined): string {',
  '    return this.withDefaults(data).escalation;',
  '  }',
  '',
  '  private withDefaults(data: IncidentNodeData | undefined): IncidentNodeData {',
  '    return data ?? {',
  "      escalation: 'On-call engineer',",
  "      owner: 'Unassigned',",
  "      priority: 'Normal',",
  "      queue: 'Operations',",
  '    };',
  '  }',
  '',
  "  private toPriority(value: string): IncidentNodeData['priority'] {",
  "    return value === 'Critical' || value === 'High' ? value : 'Normal';",
  '  }',
  '',
  '  private readValue(event: Event): string {',
  '    return event.target instanceof HTMLInputElement || event.target instanceof HTMLSelectElement',
  '      ? event.target.value',
  "      : '';",
  '  }',
  '}',
].join('\n');

const plainCssMarkup = [
  '<div class="incident-node-properties">',
  '  <aside class="incident-node-properties__nodes" aria-label="Incident nodes">',
  '    @for (node of definition().nodes; track node.id) {',
  '      <button',
  '        type="button"',
  '        [class.is-selected]="inspectedNodeId() === node.id"',
  '        (click)="selectNode(node)"',
  '      >',
  '        <span>{{ node.name }}</span>',
  '        <small>{{ node.type }}</small>',
  '      </button>',
  '    }',
  '  </aside>',
  '',
  '  <tng-flow-node-properties',
  '    [definition]="definition()"',
  '    [inspectedNodeId]="inspectedNodeId()"',
  '    [readonly]="readonly()"',
  '    [showData]="showData()"',
  '    [showPorts]="showPorts()"',
  '    (nodeChangeRequested)="applyNodeChanges($event)"',
  '  >',
  '    <ng-template',
  '      tngFlowNodePropertiesData',
  '      let-data',
  '      let-readonly="readonly"',
  '      let-requestDataChange="requestDataChange"',
  '    >',
  '      <div class="incident-node-properties__data-grid">',
  '        <label>',
  '          <span>Owner</span>',
  '          <input type="text" [value]="dataOwner(data)" [readOnly]="readonly" (input)="updateOwner(data, $event, requestDataChange)" />',
  '        </label>',
  '        <label>',
  '          <span>Queue</span>',
  '          <input type="text" [value]="dataQueue(data)" [readOnly]="readonly" (input)="updateQueue(data, $event, requestDataChange)" />',
  '        </label>',
  '        <label>',
  '          <span>Priority</span>',
  '          <select [value]="dataPriority(data)" [disabled]="readonly" (change)="updatePriority(data, $event, requestDataChange)">',
  '            @for (priority of priorities; track priority) {',
  '              <option [value]="priority">{{ priority }}</option>',
  '            }',
  '          </select>',
  '        </label>',
  '        <label>',
  '          <span>Escalation</span>',
  '          <input type="text" [value]="dataEscalation(data)" [readOnly]="readonly" (input)="updateEscalation(data, $event, requestDataChange)" />',
  '        </label>',
  '      </div>',
  '    </ng-template>',
  '  </tng-flow-node-properties>',
  '</div>',
].join('\n');

const plainCssStyles = [
  '.incident-node-properties {',
  '  display: grid;',
  '  grid-template-columns: minmax(13rem, 17rem) minmax(0, 1fr);',
  '  min-height: 36rem;',
  '  overflow: hidden;',
  '  border: 1px solid var(--tng-semantic-border-subtle);',
  '  border-radius: 0.5rem;',
  '}',
  '',
  '.incident-node-properties__nodes {',
  '  display: grid;',
  '  align-content: start;',
  '  gap: 0.5rem;',
  '  padding: 0.75rem;',
  '  border-right: 1px solid var(--tng-semantic-border-subtle);',
  '}',
  '',
  '.incident-node-properties__nodes button {',
  '  display: grid;',
  '  gap: 0.25rem;',
  '  padding: 0.65rem 0.75rem;',
  '  border: 1px solid var(--tng-semantic-border-subtle);',
  '  border-radius: 0.5rem;',
  '  background: var(--tng-semantic-background-surface);',
  '  text-align: left;',
  '}',
  '',
  '.incident-node-properties__nodes button.is-selected {',
  '  border-color: var(--tng-semantic-accent-primary);',
  '}',
  '',
  '.incident-node-properties__data-grid {',
  '  display: grid;',
  '  gap: 0.75rem;',
  '}',
  '',
  '.incident-node-properties__data-grid label {',
  '  display: grid;',
  '  gap: 0.35rem;',
  '}',
  '',
  '.incident-node-properties__data-grid input,',
  '.incident-node-properties__data-grid select {',
  '  min-height: 2.5rem;',
  '  border: 1px solid var(--tng-semantic-border-default);',
  '  border-radius: 0.5rem;',
  '}',
  '',
  '@media (max-width: 720px) {',
  '  .incident-node-properties {',
  '    grid-template-columns: 1fr;',
  '  }',
  '}',
].join('\n');

const tailwindMarkup = [
  '<div class="grid min-h-[36rem] overflow-hidden rounded-lg border border-tng-border-subtle bg-tng-bg-base md:grid-cols-[minmax(13rem,17rem)_minmax(0,1fr)]">',
  '  <aside class="grid content-start gap-2 border-b border-tng-border-subtle bg-tng-bg-muted/60 p-3 md:border-b-0 md:border-r" aria-label="Incident nodes">',
  '    @for (node of definition().nodes; track node.id) {',
  '      <button',
  '        type="button"',
  '        class="grid min-w-0 gap-1 rounded-lg border border-tng-border-subtle bg-tng-bg-surface px-3 py-2 text-left text-sm text-tng-fg-primary transition hover:bg-tng-bg-muted"',
  '        [class.border-tng-accent-primary]="inspectedNodeId() === node.id"',
  '        (click)="selectNode(node)"',
  '      >',
  '        <span class="min-w-0 font-semibold [overflow-wrap:anywhere]">{{ node.name }}</span>',
  '        <small class="min-w-0 text-xs uppercase text-tng-fg-muted">{{ node.type }}</small>',
  '      </button>',
  '    }',
  '  </aside>',
  '',
  '  <tng-flow-node-properties class="min-h-[36rem]" [definition]="definition()" [inspectedNodeId]="inspectedNodeId()" [readonly]="readonly()" [showData]="showData()" [showPorts]="showPorts()" (nodeChangeRequested)="applyNodeChanges($event)">',
  '    <ng-template tngFlowNodePropertiesData let-data let-readonly="readonly" let-requestDataChange="requestDataChange">',
  '      <div class="grid gap-3">',
  '        <label class="grid gap-1.5 text-sm text-tng-fg-secondary">',
  '          <span>Owner</span>',
  '          <input class="min-h-10 rounded-lg border border-tng-border-default bg-tng-bg-surface px-3 text-tng-fg-primary" type="text" [value]="dataOwner(data)" [readOnly]="readonly" (input)="updateOwner(data, $event, requestDataChange)" />',
  '        </label>',
  '        <label class="grid gap-1.5 text-sm text-tng-fg-secondary">',
  '          <span>Queue</span>',
  '          <input class="min-h-10 rounded-lg border border-tng-border-default bg-tng-bg-surface px-3 text-tng-fg-primary" type="text" [value]="dataQueue(data)" [readOnly]="readonly" (input)="updateQueue(data, $event, requestDataChange)" />',
  '        </label>',
  '        <label class="grid gap-1.5 text-sm text-tng-fg-secondary">',
  '          <span>Priority</span>',
  '          <select class="min-h-10 rounded-lg border border-tng-border-default bg-tng-bg-surface px-3 text-tng-fg-primary" [value]="dataPriority(data)" [disabled]="readonly" (change)="updatePriority(data, $event, requestDataChange)">',
  '            @for (priority of priorities; track priority) {',
  '              <option [value]="priority">{{ priority }}</option>',
  '            }',
  '          </select>',
  '        </label>',
  '        <label class="grid gap-1.5 text-sm text-tng-fg-secondary">',
  '          <span>Escalation</span>',
  '          <input class="min-h-10 rounded-lg border border-tng-border-default bg-tng-bg-surface px-3 text-tng-fg-primary" type="text" [value]="dataEscalation(data)" [readOnly]="readonly" (input)="updateEscalation(data, $event, requestDataChange)" />',
  '        </label>',
  '      </div>',
  '    </ng-template>',
  '  </tng-flow-node-properties>',
  '</div>',
].join('\n');

export const flowNodePropertiesExamplesPlainCssCodeTabs: readonly DocsExampleCodeTab[] =
  Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'incident-node-properties.component.ts',
      code: componentCode,
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'incident-node-properties.component.html',
      code: plainCssMarkup,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'incident-node-properties.component.css',
      code: plainCssStyles,
    },
  ]);

export const flowNodePropertiesExamplesTailwindCodeTabs: readonly DocsExampleCodeTab[] =
  Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'incident-node-properties.component.ts',
      code: componentCode,
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'incident-node-properties.component.html',
      code: tailwindMarkup,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'incident-node-properties.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);
