import type { DocsExampleCodeTab } from '../../../../../../../shared/example-panel/docs-example-panel.component';

const customNodeComponentCode = [
  "import { Component, signal } from '@angular/core';",
  'import {',
  '  TngCardComponent,',
  '  TngCardContentComponent,',
  '  TngCardDescriptionComponent,',
  '  TngCardHeaderComponent,',
  '  TngCardTitleComponent,',
  "} from '@tailng-ui/components';",
  'import {',
  '  TngFlowEditorComponent,',
  '  TngFlowNodeTemplateDirective,',
  "} from '@tailng-ui/flow';",
  "import { agentConnections, agentNodes, agentViews } from './agent-flow.data';",
  '',
  '@Component({',
  "  selector: 'app-custom-agent-flow',",
  '  standalone: true,',
  '  imports: [',
  '    TngCardComponent,',
  '    TngCardContentComponent,',
  '    TngCardDescriptionComponent,',
  '    TngCardHeaderComponent,',
  '    TngCardTitleComponent,',
  '    TngFlowEditorComponent,',
  '    TngFlowNodeTemplateDirective,',
  '  ],',
  "  templateUrl: './custom-agent-flow.component.html',",
  '})',
  'export class CustomAgentFlowComponent {',
  '  protected readonly nodes = signal(agentNodes);',
  '  protected readonly connections = agentConnections;',
  '  protected readonly nodeViews = agentViews;',
  '}',
].join('\n');

const customNodePlainMarkup = [
  '<tng-flow-editor',
  '  flowId="custom-agent-flow"',
  '  class="agent-flow"',
  '  [nodes]="nodes()"',
  '  [connections]="connections"',
  '  [nodeViews]="nodeViews"',
  '>',
  '  <ng-template tngFlowNode="model" let-node let-view="view" let-selected="selected">',
  '    <tng-card class="model-node" tone="primary" [elevated]="selected">',
  '      <tng-card-header>',
  '        <span class="model-node__eyebrow">Reasoning step</span>',
  '        <tng-card-title>{{ node.name }}</tng-card-title>',
  '        <tng-card-description>{{ node.description }}</tng-card-description>',
  '      </tng-card-header>',
  '      <tng-card-content>',
  '        <p>{{ node.data.detail }}</p>',
  '        <span class="model-node__status">',
  "          {{ view.status ?? 'idle' }} · {{ view.progress ?? 0 }}%",
  '        </span>',
  '      </tng-card-content>',
  '    </tng-card>',
  '  </ng-template>',
  '</tng-flow-editor>',
].join('\n');

const customNodeTailwindMarkup = [
  '<tng-flow-editor',
  '  flowId="custom-agent-flow"',
  '  class="block h-[29rem] min-h-[24rem]"',
  '  [nodes]="nodes()"',
  '  [connections]="connections"',
  '  [nodeViews]="nodeViews"',
  '>',
  '  <ng-template tngFlowNode="model" let-node let-view="view" let-selected="selected">',
  '    <tng-card class="block w-[17.5rem]" tone="primary" [elevated]="selected">',
  '      <tng-card-header>',
  '        <span class="text-[0.675rem] font-bold uppercase tracking-[0.1em] text-blue-500">',
  '          Reasoning step',
  '        </span>',
  '        <tng-card-title>{{ node.name }}</tng-card-title>',
  '        <tng-card-description>{{ node.description }}</tng-card-description>',
  '      </tng-card-header>',
  '      <tng-card-content>',
  '        <p class="m-0 text-sm text-slate-600 dark:text-slate-300">{{ node.data.detail }}</p>',
  '        <span',
  '          class="mt-3 inline-flex rounded-full bg-blue-500/10 px-2 py-1 text-xs font-semibold capitalize text-blue-500"',
  '        >',
  "          {{ view.status ?? 'idle' }} · {{ view.progress ?? 0 }}%",
  '        </span>',
  '      </tng-card-content>',
  '    </tng-card>',
  '  </ng-template>',
  '</tng-flow-editor>',
].join('\n');

const customNodePlainCss = [
  '.agent-flow {',
  '  display: block;',
  '  height: 29rem;',
  '  min-height: 24rem;',
  '}',
  '',
  '.model-node {',
  '  display: block;',
  '  width: 17.5rem;',
  '}',
  '',
  '.model-node__eyebrow {',
  '  color: var(--tng-semantic-accent-brand);',
  '  font-size: 0.675rem;',
  '  font-weight: 700;',
  '  letter-spacing: 0.1em;',
  '  text-transform: uppercase;',
  '}',
  '',
  '.model-node__status {',
  '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 12%, transparent);',
  '  border-radius: 999px;',
  '  color: var(--tng-semantic-accent-brand);',
  '  display: inline-flex;',
  '  margin-top: 0.75rem;',
  '  padding: 0.2rem 0.55rem;',
  '  text-transform: capitalize;',
  '}',
].join('\n');

const monitorComponentCode = [
  "import { Component } from '@angular/core';",
  "import { TngFlowEditorComponent } from '@tailng-ui/flow';",
  "import { executionConnections, executionNodes, executionViews } from './execution.data';",
  '',
  '@Component({',
  "  selector: 'app-execution-monitor',",
  '  standalone: true,',
  '  imports: [TngFlowEditorComponent],',
  "  templateUrl: './execution-monitor.component.html',",
  '})',
  'export class ExecutionMonitorComponent {',
  '  protected readonly nodes = executionNodes;',
  '  protected readonly connections = executionConnections;',
  '  protected readonly views = executionViews;',
  '}',
].join('\n');

const monitorMarkup = [
  '<tng-flow-editor',
  '  flowId="execution-monitor"',
  '  [nodes]="nodes"',
  '  [connections]="connections"',
  '  [nodeViews]="views"',
  '  mode="readonly"',
  '  [showSelectionArea]="false"',
  '/>',
].join('\n');

const branchWorkflowDefinitionDataCode = [
  "import type { TngFlowDefinition } from '@tailng-ui/flow';",
  '',
  'export const workflow: TngFlowDefinition = {',
  "  id: 'branch-and-merge',",
  "  name: 'Branch and merge workflow',",
  '  nodes: [',
  '    {',
  "      id: 'request',",
  "      type: 'source',",
  "      name: 'Incoming request',",
  "      description: 'Receive and normalize the request.',",
  '      position: { x: 60, y: 220 },',
  "      data: { detail: 'Normalized request' },",
  '      ports: [',
  "        { id: 'request', name: 'Request', direction: 'output', kind: 'data', multiple: true },",
  '      ],',
  '    },',
  '    {',
  "      id: 'fast-track',",
  "      type: 'automation',",
  "      name: 'Fast-track analysis',",
  "      description: 'Run automated policy checks.',",
  '      position: { x: 390, y: 70 },',
  "      data: { detail: 'Automated assessment' },",
  '      ports: [',
  "        { id: 'request', name: 'Request', direction: 'input', kind: 'data' },",
  "        { id: 'result', name: 'Assessment', direction: 'output', kind: 'control', side: 'bottom' },",
  '      ],',
  '    },',
  '    {',
  "      id: 'risk-review',",
  "      type: 'review',",
  "      name: 'Risk review',",
  "      description: 'Inspect exceptions in parallel.',",
  '      position: { x: 390, y: 350 },',
  "      data: { detail: 'Manual risk assessment' },",
  '      ports: [',
  "        { id: 'request', name: 'Request', direction: 'input', kind: 'data' },",
  "        { id: 'result', name: 'Review', direction: 'output', kind: 'control', side: 'top' },",
  '      ],',
  '    },',
  '    {',
  "      id: 'merge',",
  "      type: 'merge',",
  "      name: 'Merge decision',",
  "      description: 'Combine both branch results.',",
  '      position: { x: 750, y: 220 },',
  "      data: { detail: 'Combined decision' },",
  '      ports: [',
  "        { id: 'automatic', name: 'Assessment', direction: 'input', kind: 'control', side: 'top' },",
  "        { id: 'review', name: 'Review', direction: 'input', kind: 'control', side: 'bottom' },",
  "        { id: 'decision', name: 'Decision', direction: 'output', kind: 'data' },",
  '      ],',
  '    },',
  '    {',
  "      id: 'response',",
  "      type: 'response',",
  "      name: 'Publish response',",
  "      description: 'Return the merged decision.',",
  '      position: { x: 1090, y: 220 },',
  "      data: { detail: 'Final response' },",
  "      ports: [{ id: 'decision', name: 'Decision', direction: 'input', kind: 'data' }],",
  '    },',
  '  ],',
  '  connections: [',
  '    {',
  "      id: 'request-to-fast-track',",
  "      source: { nodeId: 'request', portId: 'request' },",
  "      target: { nodeId: 'fast-track', portId: 'request' },",
  '    },',
  '    {',
  "      id: 'request-to-risk-review',",
  "      source: { nodeId: 'request', portId: 'request' },",
  "      target: { nodeId: 'risk-review', portId: 'request' },",
  '    },',
  '    {',
  "      id: 'fast-track-to-merge',",
  "      source: { nodeId: 'fast-track', portId: 'result' },",
  "      target: { nodeId: 'merge', portId: 'automatic' },",
  '    },',
  '    {',
  "      id: 'risk-review-to-merge',",
  "      source: { nodeId: 'risk-review', portId: 'result' },",
  "      target: { nodeId: 'merge', portId: 'review' },",
  '    },',
  '    {',
  "      id: 'merge-to-response',",
  "      source: { nodeId: 'merge', portId: 'decision' },",
  "      target: { nodeId: 'response', portId: 'decision' },",
  '    },',
  '  ],',
  '};',
].join('\n');

const workflowDefinitionDataCode = [
  "import type { TngFlowDefinition } from '@tailng-ui/flow';",
  '',
  'export const workflow: TngFlowDefinition = {',
  "  id: 'agent-response',",
  "  name: 'Agent response workflow',",
  '  nodes: [',
  '    {',
  "      id: 'prompt',",
  "      type: 'prompt',",
  "      name: 'Prompt builder',",
  "      description: 'Assemble the system and user instructions.',",
  '      position: { x: 80, y: 140 },',
  "      data: { detail: 'Customer support policy' },",
  '      ports: [',
  "        { id: 'output', name: 'Prompt', direction: 'output', kind: 'data', multiple: true },",
  '      ],',
  '    },',
  '    {',
  "      id: 'model',",
  "      type: 'model',",
  "      name: 'Reasoning model',",
  "      description: 'Generate a grounded response.',",
  '      position: { x: 430, y: 80 },',
  "      data: { detail: 'GPT reasoning pass' },",
  '      ports: [',
  "        { id: 'input', name: 'Prompt', direction: 'input', kind: 'data' },",
  "        { id: 'output', name: 'Answer', direction: 'output', kind: 'data', multiple: true },",
  '      ],',
  '    },',
  '    {',
  "      id: 'response',",
  "      type: 'response',",
  "      name: 'Response',",
  "      description: 'Return the final answer.',",
  '      position: { x: 780, y: 140 },',
  "      data: { detail: 'Streaming response' },",
  "      ports: [{ id: 'input', name: 'Answer', direction: 'input', kind: 'data' }],",
  '    },',
  '  ],',
  '  connections: [',
  '    {',
  "      id: 'prompt-to-model',",
  "      source: { nodeId: 'prompt', portId: 'output' },",
  "      target: { nodeId: 'model', portId: 'input' },",
  '    },',
  '    {',
  "      id: 'model-to-response',",
  "      source: { nodeId: 'model', portId: 'output' },",
  "      target: { nodeId: 'response', portId: 'input' },",
  '    },',
  '  ],',
  '};',
].join('\n');

const jsonDefinitionComponentCode = [
  "import { Component } from '@angular/core';",
  "import { TngFlowEditorComponent } from '@tailng-ui/flow';",
  "import { workflow } from './workflow.data';",
  '',
  '@Component({',
  "  selector: 'app-json-workflow',",
  '  standalone: true,',
  '  imports: [TngFlowEditorComponent],',
  "  templateUrl: './json-workflow.component.html',",
  '})',
  'export class JsonWorkflowComponent {',
  '  protected readonly workflow = workflow;',
  '}',
].join('\n');

const jsonDefinitionPlainMarkup = [
  '<tng-flow-editor',
  '  class="json-workflow"',
  '  flowId="json-workflow"',
  '  ariaLabel="JSON-defined agent workflow"',
  '  [definition]="workflow"',
  '/>',
].join('\n');

const jsonDefinitionTailwindMarkup = jsonDefinitionPlainMarkup.replace(
  'class="json-workflow"',
  'class="block h-[29rem] min-h-[24rem]"',
);

const jsonDefinitionPlainCss = [
  '.json-workflow {',
  '  display: block;',
  '  height: 29rem;',
  '  min-height: 24rem;',
  '}',
].join('\n');

const gridBackgroundComponentCode = [
  "import { Component, signal } from '@angular/core';",
  "import { TngButtonComponent } from '@tailng-ui/components';",
  "import { TngFlowEditorComponent } from '@tailng-ui/flow';",
  "import { workflow } from './workflow.data';",
  '',
  '@Component({',
  "  selector: 'app-grid-background-flow',",
  '  standalone: true,',
  '  imports: [TngButtonComponent, TngFlowEditorComponent],',
  "  templateUrl: './grid-background-flow.component.html',",
  '})',
  'export class GridBackgroundFlowComponent {',
  '  protected readonly showGrid = signal(true);',
  '  protected readonly workflow = workflow;',
  '}',
].join('\n');

const gridBackgroundPlainMarkup = [
  '<div class="grid-background-demo">',
  '  <header class="grid-background-demo__toolbar">',
  '    <p>',
  '      <strong>Grid:</strong>',
  "      Background dots are {{ showGrid() ? 'visible' : 'hidden' }}.",
  '      Adaptive density and snapping remain enabled.',
  '    </p>',
  '    <tng-button',
  '      type="button"',
  '      appearance="outline"',
  '      size="sm"',
  '      [attr.aria-pressed]="showGrid()"',
  '      (click)="showGrid.set(!showGrid())"',
  '    >',
  "      {{ showGrid() ? 'Hide grid' : 'Show grid' }}",
  '    </tng-button>',
  '  </header>',
  '',
  '  <tng-flow-editor',
  '    class="grid-background-demo__canvas"',
  '    flowId="grid-background-flow"',
  '    ariaLabel="Grid background visibility example"',
  '    [definition]="workflow"',
  '    [showBackground]="showGrid()"',
  '    [snapToGrid]="true"',
  '    [gridSize]="24"',
  '    backgroundGridMode="adaptive"',
  '  />',
  '</div>',
].join('\n');

const gridBackgroundTailwindMarkup = [
  '<div class="grid gap-3">',
  '  <header',
  '    class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600 dark:border-slate-700 dark:bg-slate-900/60 dark:text-slate-300"',
  '  >',
  '    <p class="m-0">',
  '      <strong class="text-slate-950 dark:text-white">Grid:</strong>',
  "      Background dots are {{ showGrid() ? 'visible' : 'hidden' }}.",
  '      Adaptive density and snapping remain enabled.',
  '    </p>',
  '    <tng-button',
  '      type="button"',
  '      appearance="outline"',
  '      size="sm"',
  '      [attr.aria-pressed]="showGrid()"',
  '      (click)="showGrid.set(!showGrid())"',
  '    >',
  "      {{ showGrid() ? 'Hide grid' : 'Show grid' }}",
  '    </tng-button>',
  '  </header>',
  '',
  '  <tng-flow-editor',
  '    class="block h-[29rem] min-h-[24rem]"',
  '    style="--tng-flow-grid-color: color-mix(in srgb, var(--tng-semantic-foreground-secondary, #475569) 55%, transparent)"',
  '    flowId="grid-background-flow"',
  '    ariaLabel="Grid background visibility example"',
  '    [definition]="workflow"',
  '    [showBackground]="showGrid()"',
  '    [snapToGrid]="true"',
  '    [gridSize]="24"',
  '    backgroundGridMode="adaptive"',
  '  />',
  '</div>',
].join('\n');

const gridBackgroundPlainCss = [
  '.grid-background-demo {',
  '  display: grid;',
  '  gap: 0.75rem;',
  '}',
  '',
  '.grid-background-demo__toolbar {',
  '  align-items: center;',
  '  background: var(--tng-semantic-background-muted, #f8fafc);',
  '  border: 1px solid var(--tng-semantic-border-subtle, #e2e8f0);',
  '  border-radius: 0.75rem;',
  '  color: var(--tng-semantic-foreground-secondary, #475569);',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  gap: 0.75rem;',
  '  justify-content: space-between;',
  '  padding: 0.75rem 1rem;',
  '}',
  '',
  '.grid-background-demo__toolbar p {',
  '  margin: 0;',
  '}',
  '',
  '.grid-background-demo__canvas {',
  '  display: block;',
  '  height: 29rem;',
  '  min-height: 24rem;',
  '  --tng-flow-grid-color: color-mix(',
  '    in srgb,',
  '    var(--tng-semantic-foreground-secondary, #475569) 55%,',
  '    transparent',
  '  );',
  '}',
].join('\n');

const controlledPositionComponentCode = [
  "import { Component, signal } from '@angular/core';",
  "import { TngButtonComponent } from '@tailng-ui/components';",
  'import {',
  '  TngFlowEditorComponent,',
  '  type TngFlowNodePositionChange,',
  "} from '@tailng-ui/flow';",
  "import { workflow } from './workflow.data';",
  '',
  '@Component({',
  "  selector: 'app-controlled-workflow',",
  '  standalone: true,',
  '  imports: [TngButtonComponent, TngFlowEditorComponent],',
  "  templateUrl: './controlled-workflow.component.html',",
  '})',
  'export class ControlledWorkflowComponent {',
  '  protected readonly definition = signal(workflow);',
  '  protected readonly lastChange = signal<TngFlowNodePositionChange | null>(null);',
  '',
  '  protected updatePosition(event: TngFlowNodePositionChange): void {',
  '    this.lastChange.set(event);',
  '    this.definition.update((current) => ({',
  '      ...current,',
  '      nodes: current.nodes.map((node) =>',
  '        node.id === event.nodeId ? { ...node, position: event.position } : node,',
  '      ),',
  '    }));',
  '  }',
  '',
  '  protected reset(): void {',
  '    this.definition.set(workflow);',
  '    this.lastChange.set(null);',
  '  }',
  '}',
].join('\n');

const controlledPositionPlainMarkup = [
  '<div class="controlled-workflow">',
  '  <tng-flow-editor',
  '    class="controlled-workflow__canvas"',
  '    flowId="controlled-workflow"',
  '    ariaLabel="Controlled agent workflow positions"',
  '    [definition]="definition()"',
  '    (nodePositionChange)="updatePosition($event)"',
  '  />',
  '  <footer class="controlled-workflow__position-bar">',
  '    <p aria-live="polite">',
  '      @if (lastChange(); as change) {',
  '        <strong>{{ change.nodeId }}</strong>',
  '        moved to ({{ change.position.x }}, {{ change.position.y }})',
  '      } @else {',
  '        Drag a node to update the external definition signal.',
  '      }',
  '    </p>',
  '    <tng-button type="button" appearance="outline" size="sm" (click)="reset()">',
  '      Reset positions',
  '    </tng-button>',
  '  </footer>',
  '</div>',
].join('\n');

const controlledPositionTailwindMarkup = controlledPositionPlainMarkup
  .replace('class="controlled-workflow"', 'class="grid gap-3"')
  .replace('class="controlled-workflow__canvas"', 'class="block h-[29rem] min-h-[24rem]"')
  .replace(
    'class="controlled-workflow__position-bar"',
    'class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600"',
  );

const controlledPositionPlainCss = [
  '.controlled-workflow {',
  '  display: grid;',
  '  gap: 0.75rem;',
  '}',
  '',
  '.controlled-workflow__canvas {',
  '  display: block;',
  '  height: 29rem;',
  '  min-height: 24rem;',
  '}',
  '',
  '.controlled-workflow__position-bar {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  gap: 0.75rem;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  padding: 0.75rem 1rem;',
  '  border: 1px solid var(--tng-semantic-border-subtle);',
  '  border-radius: 0.75rem;',
  '  background: var(--tng-semantic-background-muted);',
  '}',
  '',
  '.controlled-workflow__position-bar p {',
  '  margin: 0;',
  '}',
].join('\n');

const connectionEditingComponentCode = [
  "import { Component, signal } from '@angular/core';",
  'import {',
  '  TngFlowEditorComponent,',
  '  type TngFlowConnectionCandidate,',
  '  type TngFlowConnectionCreateRequest,',
  '  type TngFlowConnectionReconnectRequest,',
  '  type TngFlowConnectionRejectedEvent,',
  '  type TngFlowConnectionValidation,',
  '  type TngFlowSelection,',
  "} from '@tailng-ui/flow';",
  "import { editingWorkflow } from './workflow.data';",
  '',
  '@Component({',
  "  selector: 'app-connection-editing',",
  '  standalone: true,',
  '  imports: [TngFlowEditorComponent],',
  "  templateUrl: './connection-editing.component.html',",
  '})',
  'export class ConnectionEditingComponent {',
  '  protected readonly definition = signal(editingWorkflow);',
  '  protected readonly selection = signal<TngFlowSelection>({',
  '    nodeIds: new Set(),',
  '    connectionIds: new Set(),',
  '  });',
  '  protected readonly rejection = signal<string | null>(null);',
  '  private nextConnectionId = 1;',
  '',
  '  protected readonly validateConnection = (',
  '    candidate: TngFlowConnectionCandidate,',
  '  ): TngFlowConnectionValidation => {',
  '    const sourceType = candidate.sourcePort.dataType;',
  '    const targetType = candidate.targetPort.dataType;',
  '    return sourceType === undefined || targetType === undefined || sourceType === targetType',
  '      ? { valid: true }',
  '      : {',
  '          valid: false,',
  "          code: 'incompatible-data-type',",
  '          reason: `Cannot connect ${sourceType} data to ${targetType} data.`,',
  '        };',
  '  };',
  '',
  '  protected createConnection(request: TngFlowConnectionCreateRequest): void {',
  '    this.definition.update((definition) => ({',
  '      ...definition,',
  '      connections: [',
  '        ...definition.connections,',
  "        { id: `connection-${this.nextConnectionId++}`, ...request, type: 'bezier' },",
  '      ],',
  '    }));',
  '    this.rejection.set(null);',
  '  }',
  '',
  '  protected reconnectConnection(request: TngFlowConnectionReconnectRequest): void {',
  '    this.definition.update((definition) => ({',
  '      ...definition,',
  '      connections: definition.connections.map((connection) =>',
  '        connection.id === request.connectionId',
  '          ? { ...connection, source: request.source, target: request.target }',
  '          : connection,',
  '      ),',
  '    }));',
  '    this.rejection.set(null);',
  '  }',
  '',
  '  protected rejectConnection(event: TngFlowConnectionRejectedEvent): void {',
  '    this.rejection.set(event.reason);',
  '  }',
  '}',
].join('\n');

const connectionEditingPlainMarkup = [
  '<div class="connection-example">',
  '  <tng-flow-editor',
  '    flowId="connection-editing"',
  '    class="connection-example__canvas"',
  '    [definition]="definition()"',
  '    [selection]="selection()"',
  '    [connectionValidator]="validateConnection"',
  '    (connectionCreateRequested)="createConnection($event)"',
  '    (connectionReconnectRequested)="reconnectConnection($event)"',
  '    (selectionChange)="selection.set($event)"',
  '    (connectionRejected)="rejectConnection($event)"',
  '  />',
  '  @if (rejection(); as reason) {',
  '    <p class="connection-example__error" role="alert">{{ reason }}</p>',
  '  }',
  '</div>',
].join('\n');

const connectionEditingTailwindMarkup = connectionEditingPlainMarkup
  .replace('class="connection-example"', 'class="grid gap-3"')
  .replace('class="connection-example__canvas"', 'class="block h-[29rem] min-h-[24rem]"')
  .replace(
    'class="connection-example__error"',
    'class="m-0 rounded-xl border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-700"',
  );

const connectionEditingPlainCss = [
  '.connection-example {',
  '  display: grid;',
  '  gap: 0.75rem;',
  '}',
  '',
  '.connection-example__canvas {',
  '  display: block;',
  '  height: 29rem;',
  '  min-height: 24rem;',
  '}',
  '',
  '.connection-example__error {',
  '  margin: 0;',
  '  padding: 0.75rem 1rem;',
  '  border: 1px solid var(--tng-semantic-accent-danger);',
  '  border-radius: 0.75rem;',
  '  color: var(--tng-semantic-accent-danger);',
  '}',
].join('\n');

const connectionEditingDataCode = [
  "import type { TngFlowDefinition } from '@tailng-ui/flow';",
  '',
  'export const editingWorkflow: TngFlowDefinition = {',
  "  id: 'connection-editing',",
  '  nodes: [',
  '    {',
  "      id: 'request', type: 'source', name: 'Request payload',",
  '      position: { x: 50, y: 90 },',
  '      ports: [{',
  "        id: 'payload', name: 'Text', direction: 'output', kind: 'data',",
  "        dataType: 'text', multiple: true,",
  '      }],',
  '    },',
  '    {',
  "      id: 'fallback', type: 'source', name: 'Fallback payload',",
  '      position: { x: 50, y: 320 },',
  '      ports: [{',
  "        id: 'payload', name: 'Text', direction: 'output', kind: 'data',",
  "        dataType: 'text', multiple: true,",
  '      }],',
  '    },',
  '    {',
  "      id: 'parser', type: 'transform', name: 'Parse request',",
  '      position: { x: 390, y: 190 },',
  '      ports: [',
  "        { id: 'payload', name: 'Text', direction: 'input', kind: 'data', dataType: 'text' },",
  "        { id: 'result', name: 'JSON', direction: 'output', kind: 'data', dataType: 'json', multiple: true },",
  '      ],',
  '    },',
  '    {',
  "      id: 'publish', type: 'target', name: 'Publish result',",
  '      position: { x: 760, y: 90 },',
  '      ports: [{',
  "        id: 'result', name: 'JSON', direction: 'input', kind: 'data', dataType: 'json',",
  '      }],',
  '    },',
  '    {',
  "      id: 'archive', type: 'target', name: 'Archive result',",
  '      position: { x: 760, y: 320 },',
  '      ports: [{',
  "        id: 'result', name: 'JSON', direction: 'input', kind: 'data', dataType: 'json',",
  '      }],',
  '    },',
  '  ],',
  '  connections: [{',
  "    id: 'parser-to-publish',",
  "    source: { nodeId: 'parser', portId: 'result' },",
  "    target: { nodeId: 'publish', portId: 'result' },",
  '  }],',
  '};',
].join('\n');

const selectionModesComponentCode = [
  "import { Component, signal } from '@angular/core';",
  'import {',
  '  TngFlowEditorComponent,',
  '  type TngFlowConnectionsDeleteRequest,',
  '  type TngFlowEditorMode,',
  '  type TngFlowNodesDeleteRequest,',
  '  type TngFlowSelection,',
  "} from '@tailng-ui/flow';",
  "import { selectionWorkflow } from './workflow.data';",
  '',
  '@Component({',
  "  selector: 'app-selection-modes',",
  '  standalone: true,',
  '  imports: [TngFlowEditorComponent],',
  "  templateUrl: './selection-modes.component.html',",
  '})',
  'export class SelectionModesComponent {',
  "  protected readonly modes: readonly TngFlowEditorMode[] = ['edit', 'inspect', 'readonly'];",
  '  protected readonly definition = signal(selectionWorkflow);',
  "  protected readonly mode = signal<TngFlowEditorMode>('edit');",
  '  protected readonly selection = signal<TngFlowSelection>({',
  '    nodeIds: new Set(),',
  '    connectionIds: new Set(),',
  '  });',
  '',
  '  protected setMode(mode: TngFlowEditorMode): void {',
  '    this.mode.set(mode);',
  "    if (mode === 'readonly') {",
  '      this.selection.set({ nodeIds: new Set(), connectionIds: new Set() });',
  '    }',
  '  }',
  '',
  '  protected deleteConnections(request: TngFlowConnectionsDeleteRequest): void {',
  '    const ids = new Set(request.connectionIds);',
  '    this.definition.update((definition) => ({',
  '      ...definition,',
  '      connections: definition.connections.filter((connection) => !ids.has(connection.id)),',
  '    }));',
  '  }',
  '',
  '  protected deleteNodes(request: TngFlowNodesDeleteRequest): void {',
  '    const ids = new Set(request.nodeIds);',
  '    this.definition.update((definition) => ({',
  '      ...definition,',
  '      nodes: definition.nodes.filter((node) => !ids.has(node.id)),',
  '      connections: definition.connections.filter((connection) =>',
  '        !ids.has(connection.source.nodeId) && !ids.has(connection.target.nodeId),',
  '      ),',
  '    }));',
  '  }',
  '}',
].join('\n');

const selectionModesPlainMarkup = [
  '<div class="selection-example">',
  '  <div class="selection-example__modes" aria-label="Editor mode">',
  '    @for (editorMode of modes; track editorMode) {',
  '      <button type="button" (click)="setMode(editorMode)">{{ editorMode }}</button>',
  '    }',
  '  </div>',
  '  <tng-flow-editor',
  '    flowId="selection-modes"',
  '    class="selection-example__canvas"',
  '    [definition]="definition()"',
  '    [mode]="mode()"',
  '    [selection]="selection()"',
  '    (selectionChange)="selection.set($event)"',
  '    (connectionsDeleteRequested)="deleteConnections($event)"',
  '    (nodesDeleteRequested)="deleteNodes($event)"',
  '  />',
  '</div>',
].join('\n');

const selectionModesTailwindMarkup = selectionModesPlainMarkup
  .replace('class="selection-example"', 'class="grid gap-3"')
  .replace('class="selection-example__modes"', 'class="flex flex-wrap gap-2"')
  .replace('class="selection-example__canvas"', 'class="block h-[29rem] min-h-[24rem]"');

const selectionModesPlainCss = [
  '.selection-example {',
  '  display: grid;',
  '  gap: 0.75rem;',
  '}',
  '',
  '.selection-example__modes {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  gap: 0.5rem;',
  '}',
  '',
  '.selection-example__canvas {',
  '  display: block;',
  '  height: 29rem;',
  '  min-height: 24rem;',
  '}',
].join('\n');

const selectionModesDataCode = [
  "import type { TngFlowDefinition } from '@tailng-ui/flow';",
  '',
  'export const selectionWorkflow: TngFlowDefinition = {',
  "  id: 'selection-modes',",
  '  nodes: [',
  '    {',
  "      id: 'intake', type: 'source', name: 'Intake',",
  '      position: { x: 70, y: 170 },',
  "      ports: [{ id: 'request', direction: 'output', kind: 'data', multiple: true }],",
  '    },',
  '    {',
  "      id: 'review', type: 'review', name: 'Locked review', locked: true,",
  '      position: { x: 410, y: 170 },',
  '      ports: [',
  "        { id: 'request', direction: 'input', kind: 'data' },",
  "        { id: 'decision', direction: 'output', kind: 'data', multiple: true },",
  '      ],',
  '    },',
  '    {',
  "      id: 'publish', type: 'target', name: 'Publish',",
  '      position: { x: 760, y: 170 },',
  "      ports: [{ id: 'decision', direction: 'input', kind: 'data' }],",
  '    },',
  '  ],',
  '  connections: [',
  '    {',
  "      id: 'intake-to-review',",
  "      source: { nodeId: 'intake', portId: 'request' },",
  "      target: { nodeId: 'review', portId: 'request' },",
  '    },',
  '    {',
  "      id: 'review-to-publish',",
  "      source: { nodeId: 'review', portId: 'decision' },",
  "      target: { nodeId: 'publish', portId: 'decision' },",
  '    },',
  '  ],',
  '};',
].join('\n');

type FlowCodeTabsOptions = Readonly<{
  componentTitle: string;
  componentCode: string;
  markupTitle: string;
  markup: string;
  cssTitle: string;
  css: string;
  dataCode?: string;
}>;

function flowCodeTabs(options: FlowCodeTabsOptions): readonly DocsExampleCodeTab[] {
  const { componentTitle, componentCode, markupTitle, markup, cssTitle, css, dataCode } = options;
  return Object.freeze([
    { value: 'ts', label: 'TS', language: 'ts', title: componentTitle, code: componentCode },
    { value: 'html', label: 'HTML', language: 'html', title: markupTitle, code: markup },
    { value: 'css', label: 'CSS', language: 'css', title: cssTitle, code: css },
    {
      value: 'data',
      label: 'Data',
      language: 'ts',
      title: 'workflow.data.ts',
      code: dataCode ?? workflowDefinitionDataCode,
    },
  ]);
}

export const jsonDefinitionPlainCssCodeTabs = flowCodeTabs({
  componentTitle: 'json-workflow.component.ts',
  componentCode: jsonDefinitionComponentCode,
  markupTitle: 'json-workflow.component.html',
  markup: jsonDefinitionPlainMarkup,
  cssTitle: 'json-workflow.component.css',
  css: jsonDefinitionPlainCss,
  dataCode: branchWorkflowDefinitionDataCode,
});

export const jsonDefinitionTailwindCodeTabs = flowCodeTabs({
  componentTitle: 'json-workflow.component.ts',
  componentCode: jsonDefinitionComponentCode,
  markupTitle: 'json-workflow.component.html',
  markup: jsonDefinitionTailwindMarkup,
  cssTitle: 'json-workflow.component.css',
  css: '/* Tailwind utilities are applied directly in the template. */',
  dataCode: branchWorkflowDefinitionDataCode,
});

export const gridBackgroundPlainCssCodeTabs = flowCodeTabs({
  componentTitle: 'grid-background-flow.component.ts',
  componentCode: gridBackgroundComponentCode,
  markupTitle: 'grid-background-flow.component.html',
  markup: gridBackgroundPlainMarkup,
  cssTitle: 'grid-background-flow.component.css',
  css: gridBackgroundPlainCss,
  dataCode: branchWorkflowDefinitionDataCode,
});

export const gridBackgroundTailwindCodeTabs = flowCodeTabs({
  componentTitle: 'grid-background-flow.component.ts',
  componentCode: gridBackgroundComponentCode,
  markupTitle: 'grid-background-flow.component.html',
  markup: gridBackgroundTailwindMarkup,
  cssTitle: 'grid-background-flow.component.css',
  css: '/* Tailwind utilities and the scoped grid color variable are applied directly in the template. */',
  dataCode: branchWorkflowDefinitionDataCode,
});

export const controlledPositionPlainCssCodeTabs = flowCodeTabs({
  componentTitle: 'controlled-workflow.component.ts',
  componentCode: controlledPositionComponentCode,
  markupTitle: 'controlled-workflow.component.html',
  markup: controlledPositionPlainMarkup,
  cssTitle: 'controlled-workflow.component.css',
  css: controlledPositionPlainCss,
});

export const controlledPositionTailwindCodeTabs = flowCodeTabs({
  componentTitle: 'controlled-workflow.component.ts',
  componentCode: controlledPositionComponentCode,
  markupTitle: 'controlled-workflow.component.html',
  markup: controlledPositionTailwindMarkup,
  cssTitle: 'controlled-workflow.component.css',
  css: '/* Tailwind utilities are applied directly in the template. */',
});

export const connectionEditingPlainCssCodeTabs = flowCodeTabs({
  componentTitle: 'connection-editing.component.ts',
  componentCode: connectionEditingComponentCode,
  markupTitle: 'connection-editing.component.html',
  markup: connectionEditingPlainMarkup,
  cssTitle: 'connection-editing.component.css',
  css: connectionEditingPlainCss,
  dataCode: connectionEditingDataCode,
});

export const connectionEditingTailwindCodeTabs = flowCodeTabs({
  componentTitle: 'connection-editing.component.ts',
  componentCode: connectionEditingComponentCode,
  markupTitle: 'connection-editing.component.html',
  markup: connectionEditingTailwindMarkup,
  cssTitle: 'connection-editing.component.css',
  css: '/* Tailwind utilities are applied directly in the template. */',
  dataCode: connectionEditingDataCode,
});

export const selectionModesPlainCssCodeTabs = flowCodeTabs({
  componentTitle: 'selection-modes.component.ts',
  componentCode: selectionModesComponentCode,
  markupTitle: 'selection-modes.component.html',
  markup: selectionModesPlainMarkup,
  cssTitle: 'selection-modes.component.css',
  css: selectionModesPlainCss,
  dataCode: selectionModesDataCode,
});

export const selectionModesTailwindCodeTabs = flowCodeTabs({
  componentTitle: 'selection-modes.component.ts',
  componentCode: selectionModesComponentCode,
  markupTitle: 'selection-modes.component.html',
  markup: selectionModesTailwindMarkup,
  cssTitle: 'selection-modes.component.css',
  css: '/* Tailwind utilities are applied directly in the template. */',
  dataCode: selectionModesDataCode,
});

export const customNodePlainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'custom-agent-flow.component.ts',
    code: customNodeComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'custom-agent-flow.component.html',
    code: customNodePlainMarkup,
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'custom-agent-flow.component.css',
    code: customNodePlainCss,
  },
]);

export const customNodeTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'custom-agent-flow.component.ts',
    code: customNodeComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'custom-agent-flow.component.html',
    code: customNodeTailwindMarkup,
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'custom-agent-flow.component.css',
    code: '/* Tailwind utilities are applied directly in the template. */',
  },
]);

export const monitorPlainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'execution-monitor.component.ts',
    code: monitorComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'execution-monitor.component.html',
    code: monitorMarkup.replace('flowId=', 'class="execution-monitor"\n  flowId='),
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'execution-monitor.component.css',
    code: [
      '.execution-monitor {',
      '  display: block;',
      '  height: 29rem;',
      '  min-height: 24rem;',
      '}',
    ].join('\n'),
  },
]);

export const monitorTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'execution-monitor.component.ts',
    code: monitorComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'execution-monitor.component.html',
    code: monitorMarkup.replace('flowId=', 'class="block h-[29rem] min-h-[24rem]"\n  flowId='),
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'execution-monitor.component.css',
    code: '/* Tailwind utilities are applied directly in the template. */',
  },
]);
