import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';

const controlledWorkbenchComponentCode = [
  "import { Component, computed, signal } from '@angular/core';",
  'import {',
  '  TngFlowWorkbenchComponent,',
  '  type TngFlowRunExecutionSnapshot,',
  '  type TngFlowWorkbenchMode,',
  '  type TngFlowWorkbenchState,',
  "} from '@tailng-ui/flow/execution';",
  'import {',
  '  type TngFlowConnection,',
  '  type TngFlowConnectionsDeleteRequest,',
  '  type TngFlowDefinition,',
  '  type TngFlowNode,',
  '  type TngFlowNodeCreateRequest,',
  '  type TngFlowNodesMovedEvent,',
  '  type TngFlowNodesDeleteRequest,',
  '  type TngFlowPaletteItem,',
  '  type TngFlowSelection,',
  "} from '@tailng-ui/flow';",
  "import { agentConnections, agentNodes } from './agent-flow.data';",
  '',
  'type AgentNodeData = Readonly<{ detail: string }>;',
  '',
  'const paletteItems: readonly TngFlowPaletteItem<AgentNodeData>[] = [',
  '  {',
  "    id: 'human-review-catalog-item',",
  "    type: 'review',",
  "    name: 'Human review',",
  "    description: 'Pause the workflow for an approval decision.',",
  "    data: { detail: 'Manual approval required' },",
  '  },',
  '];',
  '',
  'const modes: readonly { value: TngFlowWorkbenchMode; label: string }[] = [',
  "  { value: 'create', label: 'Create' },",
  "  { value: 'edit', label: 'Edit' },",
  "  { value: 'inspect', label: 'Inspect' },",
  "  { value: 'view', label: 'View' },",
  "  { value: 'live', label: 'Live' },",
  '];',
  '',
  'const snapshot = {',
  "  id: 'support-agent-run',",
  "  definitionId: 'support-agent-flow',",
  "  phase: 'active',",
  '  progress: 68,',
  "  statusMessage: 'Generating the final response',",
  '  nodeExecutions: [',
  "    { id: 'prompt-run', nodeId: 'prompt', activationId: 'run', attempt: 1, phase: 'succeeded' },",
  "    { id: 'model-run', nodeId: 'model', activationId: 'run', attempt: 1, phase: 'active', progress: 68 },",
  "    { id: 'response-run', nodeId: 'response', activationId: 'run', attempt: 1, phase: 'waiting' },",
  '  ],',
  '  connectionExecutions: [',
  "    { id: 'prompt-to-model-run', connectionId: 'prompt-to-model', activationId: 'run', attempt: 1, phase: 'succeeded' },",
  "    { id: 'model-to-response-run', connectionId: 'model-to-response', activationId: 'run', attempt: 1, phase: 'active' },",
  '  ],',
  '} satisfies TngFlowRunExecutionSnapshot<unknown>;',
  '',
  'const emptySelection = (): TngFlowSelection => ({',
  '  nodeIds: new Set<string>(),',
  '  connectionIds: new Set<string>(),',
  '});',
  '',
  '@Component({',
  "  selector: 'app-agent-workbench',",
  '  standalone: true,',
  '  imports: [TngFlowWorkbenchComponent],',
  "  templateUrl: './agent-workbench.component.html',",
  "  styleUrl: './agent-workbench.component.css',",
  '})',
  'export class AgentWorkbenchComponent {',
  '  protected readonly nodes = signal<readonly TngFlowNode<AgentNodeData>[]>(agentNodes);',
  '  protected readonly connections = signal<readonly TngFlowConnection[]>(agentConnections);',
  '  protected readonly selection = signal<TngFlowSelection>(emptySelection());',
  "  protected readonly inspectedNodeId = signal<string | null>('model');",
  "  protected readonly mode = signal<TngFlowWorkbenchMode>('edit');",
  '  protected readonly paletteOpen = signal(true);',
  '  protected readonly detailsOpen = signal(true);',
  "  protected readonly state = signal<TngFlowWorkbenchState>('ready');",
  '  protected readonly paletteItems = paletteItems;',
  '  protected readonly modes = modes;',
  '  protected readonly snapshot = snapshot;',
  '  protected readonly definition = computed<TngFlowDefinition<AgentNodeData>>(() => ({',
  "    id: 'support-agent-flow',",
  "    name: 'Support agent flow',",
  '    nodes: this.nodes(),',
  '    connections: this.connections(),',
  '  }));',
  '  private nodeSequence = 0;',
  '',
  '  protected onNodeCreate(event: TngFlowNodeCreateRequest<AgentNodeData>): void {',
  '    const id = `${event.item.type}-${this.nodeSequence++}`;',
  '    this.nodes.update((nodes) => [',
  '      ...nodes,',
  '      {',
  '        id,',
  '        type: event.item.type,',
  '        name: event.item.name,',
  '        description: event.item.description,',
  '        data: event.item.data,',
  '        position: event.position,',
  '        ports: [],',
  '      },',
  '    ]);',
  '    this.selection.set({ nodeIds: new Set([id]), connectionIds: new Set() });',
  '    this.inspectedNodeId.set(id);',
  '  }',
  '',
  '  protected onNodesMoved(event: TngFlowNodesMovedEvent): void {',
  '    const positions = new Map(event.nodes.map((node) => [node.id, node.position]));',
  '    this.nodes.update((nodes) =>',
  '      nodes.map((node) => ({ ...node, position: positions.get(node.id) ?? node.position })),',
  '    );',
  '  }',
  '',
  '  protected deleteConnections(request: TngFlowConnectionsDeleteRequest): void {',
  '    const deletedIds = new Set(request.connectionIds);',
  '    this.connections.update((connections) =>',
  '      connections.filter((connection) => !deletedIds.has(connection.id)),',
  '    );',
  '    this.selection.update((selection) => ({',
  '      nodeIds: selection.nodeIds,',
  '      connectionIds: new Set(',
  '        [...selection.connectionIds].filter((connectionId) => !deletedIds.has(connectionId)),',
  '      ),',
  '    }));',
  '  }',
  '',
  '  protected deleteNodes(request: TngFlowNodesDeleteRequest): void {',
  '    const deletedIds = new Set(request.nodeIds);',
  '    this.nodes.update((nodes) => nodes.filter((node) => !deletedIds.has(node.id)));',
  '    this.connections.update((connections) =>',
  '      connections.filter(',
  '        (connection) =>',
  '          !deletedIds.has(connection.source.nodeId) && !deletedIds.has(connection.target.nodeId),',
  '      ),',
  '    );',
  '    this.selection.set(emptySelection());',
  '    const inspectedNodeId = this.inspectedNodeId();',
  '    if (inspectedNodeId !== null && deletedIds.has(inspectedNodeId)) {',
  '      this.inspectedNodeId.set(null);',
  '    }',
  '  }',
  '',
  '  protected togglePalette(): void {',
  '    this.paletteOpen.update((open) => !open);',
  '  }',
  '',
  '  protected toggleDetails(): void {',
  '    this.detailsOpen.update((open) => !open);',
  '  }',
  '',
  '  protected onSelectionChange(selection: TngFlowSelection): void {',
  '    this.selection.set(selection);',
  '    this.inspectedNodeId.set([...selection.nodeIds][0] ?? null);',
  '  }',
  '}',
].join('\n');

const plainCssWorkbenchMarkup = [
  '<div class="agent-workbench-toolbar">',
  '  <div class="agent-workbench-modes" aria-label="Workbench mode">',
  '    @for (item of modes; track item.value) {',
  '      <button type="button" [class.is-active]="mode() === item.value" (click)="mode.set(item.value)">',
  '        {{ item.label }}',
  '      </button>',
  '    }',
  '  </div>',
  '  <div class="agent-workbench-panels" aria-label="Workbench panels">',
  '    <button',
  '      type="button"',
  "      [disabled]=\"mode() !== 'create' && mode() !== 'edit'\"",
  '      (click)="togglePalette()"',
  '    >',
  "      {{ paletteOpen() ? 'Hide palette' : 'Show palette' }}",
  '    </button>',
  '    <button',
  '      type="button"',
  '      [disabled]="mode() === \'view\'"',
  '      (click)="toggleDetails()"',
  '    >',
  "      {{ detailsOpen() ? 'Hide details' : 'Show details' }}",
  '    </button>',
  '  </div>',
  '</div>',
  '',
  '<tng-flow-workbench',
  '  flowId="support-agent-workbench"',
  '  class="agent-workbench"',
  '  detailsKind="auto"',
  '  paletteAriaLabel="Agent workflow node palette"',
  '  ariaLabel="Editable support agent workbench"',
  '  [definition]="definition()"',
  '  [snapshot]="snapshot"',
  '  [mode]="mode()"',
  '  attachmentLayout="custom-points"',
  '  [paletteOpen]="paletteOpen()"',
  '  [detailsOpen]="detailsOpen()"',
  '  [showPaletteToggle]="false"',
  '  [showDetailsToggle]="false"',
  '  [selection]="selection()"',
  '  [inspectedNodeId]="inspectedNodeId()"',
  '  [state]="state()"',
  '  [paletteItems]="paletteItems"',
  '  [showMinimap]="true"',
  '  [smartGuides]="{ enabled: true, disableModifier: \'alt\' }"',
  '  (nodeCreateRequested)="onNodeCreate($event)"',
  '  (nodesMoved)="onNodesMoved($event)"',
  '  (connectionsDeleteRequested)="deleteConnections($event)"',
  '  (nodesDeleteRequested)="deleteNodes($event)"',
  '  (paletteOpenChange)="paletteOpen.set($event)"',
  '  (detailsOpenChange)="detailsOpen.set($event)"',
  '  (selectionChange)="onSelectionChange($event)"',
  '  (inspectedNodeIdChange)="inspectedNodeId.set($event)"',
  '/>',
].join('\n');

const tailwindWorkbenchMarkup = [
  '<div class="flex flex-wrap items-center justify-between gap-2">',
  '  <div class="flex flex-wrap gap-2" aria-label="Workbench mode">',
  '    @for (item of modes; track item.value) {',
  '      <button',
  '        type="button"',
  '        class="rounded-md border px-3 py-1 text-sm"',
  '        [class.bg-black]="mode() === item.value"',
  '        [class.text-white]="mode() === item.value"',
  '        (click)="mode.set(item.value)"',
  '      >',
  '        {{ item.label }}',
  '      </button>',
  '    }',
  '  </div>',
  '  <div class="flex flex-wrap gap-2" aria-label="Workbench panels">',
  '    <button',
  '      type="button"',
  '      class="rounded-md border px-3 py-1 text-sm"',
  "      [disabled]=\"mode() !== 'create' && mode() !== 'edit'\"",
  '      (click)="togglePalette()"',
  '    >',
  "      {{ paletteOpen() ? 'Hide palette' : 'Show palette' }}",
  '    </button>',
  '    <button',
  '      type="button"',
  '      class="rounded-md border px-3 py-1 text-sm"',
  '      [disabled]="mode() === \'view\'"',
  '      (click)="toggleDetails()"',
  '    >',
  "      {{ detailsOpen() ? 'Hide details' : 'Show details' }}",
  '    </button>',
  '  </div>',
  '</div>',
  '',
  '<tng-flow-workbench',
  '  flowId="support-agent-workbench"',
  '  class="block [--tng-flow-workbench-height:34rem] [--tng-flow-workbench-min-height:28rem] [--tng-flow-workbench-palette-width:16rem] max-[720px]:[--tng-flow-workbench-height:30rem]"',
  '  detailsKind="auto"',
  '  paletteAriaLabel="Agent workflow node palette"',
  '  ariaLabel="Editable support agent workbench"',
  '  [definition]="definition()"',
  '  [snapshot]="snapshot"',
  '  [mode]="mode()"',
  '  attachmentLayout="custom-points"',
  '  [paletteOpen]="paletteOpen()"',
  '  [detailsOpen]="detailsOpen()"',
  '  [showPaletteToggle]="false"',
  '  [showDetailsToggle]="false"',
  '  [selection]="selection()"',
  '  [inspectedNodeId]="inspectedNodeId()"',
  '  [state]="state()"',
  '  [paletteItems]="paletteItems"',
  '  [showMinimap]="true"',
  '  [smartGuides]="{ enabled: true, disableModifier: \'alt\' }"',
  '  (nodeCreateRequested)="onNodeCreate($event)"',
  '  (nodesMoved)="onNodesMoved($event)"',
  '  (connectionsDeleteRequested)="deleteConnections($event)"',
  '  (nodesDeleteRequested)="deleteNodes($event)"',
  '  (paletteOpenChange)="paletteOpen.set($event)"',
  '  (detailsOpenChange)="detailsOpen.set($event)"',
  '  (selectionChange)="onSelectionChange($event)"',
  '  (inspectedNodeIdChange)="inspectedNodeId.set($event)"',
  '/>',
].join('\n');

export const flowWorkbenchOverviewPlainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'agent-workbench.component.ts',
    code: controlledWorkbenchComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'agent-workbench.component.html',
    code: plainCssWorkbenchMarkup,
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'agent-workbench.component.css',
    code: [
      '.agent-workbench {',
      '  --tng-flow-workbench-height: 34rem;',
      '  --tng-flow-workbench-min-height: 28rem;',
      '  --tng-flow-workbench-palette-width: 16rem;',
      '}',
      '',
      '.agent-workbench-toolbar,',
      '.agent-workbench-modes,',
      '.agent-workbench-panels {',
      '  display: flex;',
      '  flex-wrap: wrap;',
      '  gap: 0.5rem;',
      '}',
      '',
      '.agent-workbench-toolbar {',
      '  justify-content: space-between;',
      '}',
      '',
      '.agent-workbench-modes button,',
      '.agent-workbench-panels button {',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 0.375rem;',
      '  padding: 0.25rem 0.75rem;',
      '}',
      '',
      '.agent-workbench-modes button.is-active {',
      '  background: #0f172a;',
      '  color: #fff;',
      '}',
      '',
      '@media (max-width: 720px) {',
      '  .agent-workbench {',
      '    --tng-flow-workbench-height: 30rem;',
      '  }',
      '}',
    ].join('\n'),
  },
]);

export const flowWorkbenchOverviewTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'agent-workbench.component.ts',
    code: controlledWorkbenchComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'agent-workbench.component.html',
    code: tailwindWorkbenchMarkup,
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'agent-workbench.component.css',
    code: '/* Tailwind utilities are applied directly in the template. */',
  },
]);
